# Generated by Django 2.0.9 on 2018-12-09 18:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compra',
            new_name='Producto',
        ),
    ]
