# Generated by Django 2.0.9 on 2018-12-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_auto_20181209_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='published_date',
        ),
    ]
